/**
 * \file	edroombp_main_cmp_ut.cpp
 *
 * \brief	This file instances and executes all tests of the edroombp (Basic
 * 			Libraries) layer
 *
 * \author	Santiago Carmona Meco, <scarmona@srg.aut.uah.es>
 * \internal
 * Created: 	09-sept-2014
 * Compiler: 	gcc,g++
 * Company:  Space Research Group, Universidad de Alcalá.
 * Copyright: Copyright (c) 2014, Santiago Carmona Meco
 *
 * For further information, please visit http://srg.aut.uah.es
 *
 * This software is provided under the terms of the GNU General Public v2
 * Licence. A full copy of the GNU GPL is provided in the file COPYING
 * found in the development root of the project.
 *
 */

#include "nulldomain_iface_v1.h"
#include "ut_edroombp_pr_task_iface_v1.h"
#include "ut_edroombp_pr_semaphore_iface_v1.h"
#include "ut_edroombp_pr_time_iface_v1.h"
#include "ut_edroombp_pr_irq_iface_v1.h"
#include "config.h"

#define MANDANGA

int nulldomain_main_cmp_run(int argc, ...)
{

 	/*Time Manager*/
	//OK
	{
		CUT_EDROOMBP_PR_TIME_OVERLOADED_OPERATORS CUT_EDROOMBP_PR_TIME_OVERLOADED_OPERATORS_TEST("CUT_EDROOMBP_PR_TIME_OVERLOADED_OPERATORS_TEST");
		CUT_EDROOMBP_PR_TIME_OVERLOADED_OPERATORS_TEST.PrintReport(CUT_EDROOMBP_PR_TIME_OVERLOADED_OPERATORS_TEST.DoTest());
	}

 	/*---------- val_02_03_040 ---------*/
	//OK PERO SE TIENE QUE REVISAR
	{
		CUT_EDROOMBP_PR_TIME_DELAY_IN_DELAY_AT CUT_EDROOMBP_PR_TIME_DELAY_IN_DELAY_AT_TEST("CUT_EDROOMBP_PR_TIME_DELAY_IN_DELAY_AT_TEST");
		CUT_EDROOMBP_PR_TIME_DELAY_IN_DELAY_AT_TEST.PrintReport(CUT_EDROOMBP_PR_TIME_DELAY_IN_DELAY_AT_TEST.DoTest());
	}

	/* Task */

	//OK
	{
		CUT_EDROOMBP_PR_TASK_CREATION_AND_START CUT_EDROOMBP_PR_TASK_CREATION_AND_START_TEST("CUT_EDROOMBP_PR_TASK_CREATION_AND_START_TEST");
		CUT_EDROOMBP_PR_TASK_CREATION_AND_START_TEST.PrintReport(CUT_EDROOMBP_PR_TASK_CREATION_AND_START_TEST.DoTest());
	}

	/*---------- val_02_03_060 ---------*/
	//OK
	{
		CUT_EDROOMBP_PR_TASK_CHANGE_PRIORITIES_OPERATIONS CUT_EDROOMBP_PR_TASK_CHANGE_PRIORITIES_OPERATIONS_TEST("CUT_EDROOMBP_PR_TASK_CHANGE_PRIORITIES_OPERATIONS_TEST");
		CUT_EDROOMBP_PR_TASK_CHANGE_PRIORITIES_OPERATIONS_TEST.PrintReport(CUT_EDROOMBP_PR_TASK_CHANGE_PRIORITIES_OPERATIONS_TEST.DoTest());
	}

	/*---------- val_02_03_102 ---------*/
	//OK
	{
		CUT_EDROOMBP_PR_TASK_SEND_AND_RECEIVE CUT_EDROOMBP_PR_TASK_SEND_AND_RECEIVE_TEST("CUT_EDROOMBP_PR_TASK_SEND_AND_RECEIVE_TEST");
		CUT_EDROOMBP_PR_TASK_SEND_AND_RECEIVE_TEST.PrintReport(CUT_EDROOMBP_PR_TASK_SEND_AND_RECEIVE_TEST.DoTest());

		CUT_EDROOMBP_PR_TASK_RECEIVE_AND_SEND CUT_EDROOMBP_PR_TASK_RECEIVE_AND_SEND_TEST("CUT_EDROOMBP_PR_TASK_RECEIVE_AND_SEND_TEST");
		CUT_EDROOMBP_PR_TASK_RECEIVE_AND_SEND_TEST.PrintReport(CUT_EDROOMBP_PR_TASK_RECEIVE_AND_SEND_TEST.DoTest());
	}

	//OK
	/*---------- val_02_03_101 ---------*/
	{
		CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_FIFO CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_FIFO_TEST("CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_FIFO_TEST");
		CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_FIFO_TEST.PrintReport(CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_FIFO_TEST.DoTest());
	}
	/*---------- val_02_03_103 ---------*/
	//
	{
	//OK
		CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_INHERIT CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_INHERIT_TEST("CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_INHERIT_TEST");
		CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_INHERIT_TEST.PrintReport(CUT_EDROOMBP_PR_TASK_CHANGE_TASK_PRIORITY_QUEUED_INHERIT_TEST.DoTest());
	}

	
	/*Semaphore Manager*/
	//OK
	{
		CUT_EDROOMBP_PR_SEMAPHORE_COUNTING CUT_EDROOMBP_PR_SEMAPHORE_COUNTING_TEST("CUT_EDROOMBP_PR_SEMAPHORE_COUNTING_TEST");
		CUT_EDROOMBP_PR_SEMAPHORE_COUNTING_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_COUNTING_TEST.DoTest());
	}
	/*---------- val_02_04_030 ---------*/
	//OK
	{
		CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL_TEST("CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL_TEST");
		CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL_TEST.DoTest());
	}
	//OK DELAYIN
	{
		CUT_EDROOMBP_PR_SEMAPHORE_WAIT_COND CUT_EDROOMBP_PR_SEMAPHORE_WAIT_COND_TEST("CUT_EDROOMBP_PR_SEMAPHORE_WAIT_COND_TEST");
		CUT_EDROOMBP_PR_SEMAPHORE_WAIT_COND_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_WAIT_COND_TEST.DoTest());
	}

	// OK DELAYIN
	{
		CUT_EDROOMBP_PR_SEMAPHORE_WAIT_TIMED CUT_EDROOMBP_PR_SEMAPHORE_WAIT_TIMED_TEST("CUT_EDROOMBP_PR_SEMAPHORE_WAIT_TIMED_TEST");
		CUT_EDROOMBP_PR_SEMAPHORE_WAIT_TIMED_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_WAIT_TIMED_TEST.DoTest());
	}

	//OK DELAYIN
	{
		CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL_2 CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL_2_TEST("CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL_2_TEST");
		CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL_2_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_WAIT_AND_SIGNAL_2_TEST.DoTest());
	}

 	/*---------- val_02_04_020 ---------*/
	//OK DELAYIN
	{
		CUT_EDROOMBP_PR_SEMAPHORE_DELETE_SEMAPHORES CUT_EDROOMBP_PR_SEMAPHORE_DELETE_SEMAPHORES_TEST("CUT_EDROOMBP_PR_SEMAPHORE_DELETE_SEMAPHORES_TEST");
		CUT_EDROOMBP_PR_SEMAPHORE_DELETE_SEMAPHORES_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_DELETE_SEMAPHORES_TEST.DoTest());
	}

 	/*---------- val_02_04_080 ---------*/
	//OK
	{
		CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_1 CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_1_TEST("CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_1_TEST");
		CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_1_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_1_TEST.DoTest());
	}

 	/*---------- val_02_04_090 ---------*/
	// NOOOOO
	// {
	// 	CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_2 CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_2_TEST("CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_2_TEST");
	// 	CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_2_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_PRIORITY_INHERITANCE_2_TEST.DoTest());
	// }

 	/*---------- val_02_04_110 ---------*/
	// OK 
	{
		CUT_EDROOMBP_PR_SEMAPHORE_SEMAPHORE_NESTED_OBTAIN CUT_EDROOMBP_PR_SEMAPHORE_SEMAPHORE_NESTED_OBTAIN_TEST("CUT_EDROOMBP_PR_SEMAPHORE_SEMAPHORE_NESTED_OBTAIN_TEST");
		CUT_EDROOMBP_PR_SEMAPHORE_SEMAPHORE_NESTED_OBTAIN_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_SEMAPHORE_NESTED_OBTAIN_TEST.DoTest());
	}

 	/*---------- val_02_04_120 ---------*/
	//OK
	{
		CUT_EDROOMBP_PR_SEMAPHORE_QUEUEING_DISCIPLINE CUT_EDROOMBP_PR_SEMAPHORE_QUEUEING_DISCIPLINE_TEST("CUT_EDROOMBP_PR_SEMAPHORE_QUEUEING_DISCIPLINE_TEST");
		CUT_EDROOMBP_PR_SEMAPHORE_QUEUEING_DISCIPLINE_TEST.PrintReport(CUT_EDROOMBP_PR_SEMAPHORE_QUEUEING_DISCIPLINE_TEST.DoTest());
	}


 	/*IRQ Manager*/
 	/*---------- val_02_07_010 ---------*/
	// {
	// 	CUT_EDROOMBP_PR_IRQ_MANAGER_INSTALL_HANDLER CUT_EDROOMBP_PR_IRQ_MANAGER_INSTALL_HANDLER_TEST("CUT_EDROOMBP_PR_IRQ_MANAGER_INSTALL_HANDLER_TEST");
	// 	CUT_EDROOMBP_PR_IRQ_MANAGER_INSTALL_HANDLER_TEST.PrintReport(CUT_EDROOMBP_PR_IRQ_MANAGER_INSTALL_HANDLER_TEST.DoTest());
	// }


 	/*---------- val_02_07_020 ---------*/
	// {
	// 	CUT_EDROOMBP_PR_IRQ_MANAGER_RELEASE_SEMAPHORE CUT_EDROOMBP_PR_IRQ_MANAGER_RELEASE_SEMAPHORE_TEST("CUT_EDROOMBP_PR_IRQ_MANAGER_RELEASE_SEMAPHORE_TEST");
	// 	CUT_EDROOMBP_PR_IRQ_MANAGER_RELEASE_SEMAPHORE_TEST.PrintReport(CUT_EDROOMBP_PR_IRQ_MANAGER_RELEASE_SEMAPHORE_TEST.DoTest());
	// }


	/*---------- val_02_07_040 ---------*/
// 	{
// 		CUT_EDROOMBP_PR_IRQ_MANAGER_TIMER_OPERATIONS CUT_EDROOMBP_PR_IRQ_MANAGER_TIMER_OPERATIONS_TEST("CUT_EDROOMBP_PR_IRQ_MANAGER_TIMER_OPERATIONS_TEST");
// 		CUT_EDROOMBP_PR_IRQ_MANAGER_TIMER_OPERATIONS_TEST.PrintReport(CUT_EDROOMBP_PR_IRQ_MANAGER_TIMER_OPERATIONS_TEST.DoTest());
// 	}

	/*---------- val_02_07_070 ---------*/
// 	{
// 		CUT_EDROOMBP_PR_IRQ_MANAGER_ENABLE_DISABLE CUT_EDROOMBP_PR_IRQ_MANAGER_ENABLE_DISABLE_TEST("CUT_EDROOMBP_PR_IRQ_MANAGER_ENABLE_DISABLE_TEST");
// 		CUT_EDROOMBP_PR_IRQ_MANAGER_ENABLE_DISABLE_TEST.PrintReport(CUT_EDROOMBP_PR_IRQ_MANAGER_ENABLE_DISABLE_TEST.DoTest());
// 	}

	/*IRQ Event*/
// 	/*---------- val_02_08_010 ---------*/
	// {
	// 	CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT_TEST("CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT_TEST");
	// 	CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT_TEST.PrintReport(CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT_TEST.DoTest());

	// 	CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT_COND CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT_COND_TEST("CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT_COND_TEST");
	// 	CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT_COND_TEST.PrintReport(CUT_EDROOMBP_PR_IRQ_EVENT_RECEIVE_WAIT_COND_TEST.DoTest());
	
	// }
	/*---------- val_02_07_020 ---------*/
// 	{

// 		CUT_EDROOMBP_PR_IRQ_EVENT_SEND_WAIT_COND CUT_EDROOMBP_PR_IRQ_EVENT_SEND_WAIT_COND_TEST("CUT_EDROOMBP_PR_IRQ_EVENT_SEND_WAIT_COND_TEST");
// 		CUT_EDROOMBP_PR_IRQ_EVENT_SEND_WAIT_COND_TEST.PrintReport(CUT_EDROOMBP_PR_IRQ_EVENT_SEND_WAIT_COND_TEST.DoTest());

// 	}

	

	return 0;

}
